/* Copyright © 2026 Zenin Easa Panthakkalakath */

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildModels } from './buildModels.mjs';
import { fintechRoot, konjugateModule } from './konjugatePaths.mjs';

const { createPackageArchive } = await import(pathToFileURL(konjugateModule('src/packageArchive.mjs')));

const packageDirectory = join(fintechRoot, 'packages', 'engine');
const outputDirectory = join(fintechRoot, 'out');

const manifest = JSON.parse(await readFile(join(packageDirectory, 'plugin.json'), 'utf8'));
const files = {};
// Example models are generated from scripts/buildModels.mjs into out/models and shipped inside the
// package, next to a hand-written guide from guides/, so the package always carries the model the
// generator currently writes.
const builtModels = await buildModels(join(outputDirectory, 'models'));
for (const contribution of manifest.contributes) {
    if (contribution.kind === 'example') {
        const built = builtModels.find((model) => model.name === contribution.exampleId);
        if (!built) throw new Error(`No generated model for example ${contribution.exampleId}.`);
        files[contribution.entry] = await readFile(built.path);
        if (contribution.guide) files[contribution.guide] = await readFile(join(fintechRoot, 'guides', `${contribution.exampleId}.md`));
        // Generated by scripts/generateExampleThumbnails.mjs (npm run generate:example-thumbnails),
        // the same way core regenerates its own bundled examples' thumbnails: by actually driving
        // the app, not by hand-authoring an image that could silently drift from the real model.
        if (contribution.thumbnail) files[contribution.thumbnail] = await readFile(join(fintechRoot, 'thumbnails', `${contribution.exampleId}.png`));
    } else {
        files[contribution.entry] = await readFile(join(packageDirectory, contribution.entry));
    }
}
const archive = createPackageArchive({
    packageManifest: {
        format: 'konjugate-package', formatVersion: 1, packageType: 'plugin',
        packageId: manifest.pluginId, name: manifest.name, version: manifest.version,
        contents: { manifest: 'plugin.json' }
    },
    contributionManifest: manifest,
    files
});
await mkdir(outputDirectory, { recursive: true });
const target = join(outputDirectory, `${manifest.pluginId}-${manifest.version}.kjp`);
await writeFile(target, archive);
console.log(`Built ${target}`);

// ---- the Fintech Toolbox add-on (unified launcher for all fintech tools) --------------------------
// It carries its own copy of the bundle and node definitions its importers build models from, taken from
// the plugin's components at build time so the two can never drift.
const toolboxDirectory = join(fintechRoot, 'packages', 'toolbox');
const toolboxManifest = JSON.parse(await readFile(join(toolboxDirectory, 'addon.json'), 'utf8'));
const toolboxFiles = {};
const collectToolbox = async (directory, prefix = '') => {
    for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
        const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
        if (entry.isDirectory()) await collectToolbox(directory, relative);
        else if (relative !== 'addon.json') toolboxFiles[relative] = await readFile(join(directory, relative));
    }
};
await collectToolbox(toolboxDirectory);
for (const id of ['commercialBank', 'depositorWallets', 'centralBank', 'assetMarket', 'depositRun', 'fireSale', 'interbankLendingScaled', 'interbankDefault', 'emergencyLending']) {
    toolboxFiles[`bundles/${id}.json`] = await readFile(join(packageDirectory, 'components', `${id}.json`));
}
const toolboxArchive = createPackageArchive({
    packageManifest: {
        format: 'konjugate-package', formatVersion: 1, packageType: 'addon',
        packageId: toolboxManifest.addonId, name: toolboxManifest.name, version: toolboxManifest.version,
        contents: { manifest: 'addon.json' }
    },
    contributionManifest: toolboxManifest,
    files: toolboxFiles
});
const toolboxTarget = join(outputDirectory, `${toolboxManifest.addonId}-${toolboxManifest.version}.kja`);
await writeFile(toolboxTarget, toolboxArchive);
console.log(`Built ${toolboxTarget}`);
